# Cadenas de Markov

Revise este video (visitado en julio 2023) [Markov Chains Clearly Explained! Part - 1](https://youtu.be/i3AkTO9HLXo)

Sólo a modo de referencia la playlist completa [Markov Chains Clearly Explained!](https://www.youtube.com/playlist?list=PLM8wYQRetTxBkdvBtz-gw8b9lcVkdXQKV)


Tomemos el ejemplo de cadena de Markov del video.

[imagen](/content/drive/MyDrive/__GitHub/Recursos-para-docencia/Asignaturas/IA/imagenes/Cadena de restaurante.png)


## Estadio estacionario



## ¿Y en Python?
El siguiente es el código que resuelve el problema planteado en el video:

In [1]:
import numpy as np

# Creamos una matriz
A = np.array([(0.2, 0.6, 0.2),
 (0.3,   0, 0.7),
  (0.5,   0, 0.5)
  ])

# mostramos el contenido de la matriz A:
print(A)


[[0.2 0.6 0.2]
 [0.3 0.  0.7]
 [0.5 0.  0.5]]


Seguimos calculando con los vectores pi1 y pi2

Primero pi1

In [3]:

# Creamos el vector pi0
pi0 = np.array([0,1,0])

# Calculamos el vector pi1 usando el producto punto con A
pi1 = pi0.dot(A)
# Mostramos el contenido del vector pi1:
print(pi1)

[0.3 0.  0.7]


Ahora pi2:

In [4]:
# pi2 por A
pi2 = pi1.dot(A)
# Mostramos el contenido del vector pi1:
print(pi2)

[0.41 0.18 0.41]


Finalmente pi2 * A, que sí es un estado estacionario.

In [6]:
resultado = pi2.dot(A)
print(resultado)

[0.341 0.246 0.413]
