# Cadenas de Markov


## EN CONSTRUCCIÓN 


Revise este video (visitado en julio 2023) [Markov Chains Clearly Explained! Part - 1](https://youtu.be/i3AkTO9HLXo)

Sólo a modo de referencia la playlist completa [Markov Chains Clearly Explained!](https://www.youtube.com/playlist?list=PLM8wYQRetTxBkdvBtz-gw8b9lcVkdXQKV)


La siguiente es una imagen extraída del video referenciado anteriormente y es un ejemplo de una **Cadena de Markov** 




![Cadena de ejemplo del restaurante](../imagenes/cadena-de-restaurante.png)

**Propiedades de una Cadena de Markov:**

- un estado depende exclusivamente del estado previo.

Matemáticamente:

$P(X_n=x|X_1=x_1,X_2=x_2,...,X_{n-1}=x_{n-1}) = P(X_n=x_n|X_{n-1}=x_{n-1})$

## Estadio estacionario



## ¿Y en Python?
El siguiente es el código que resuelve el problema planteado en el video:

In [1]:
import numpy as np

# Creamos una matriz
A = np.array([(0.2, 0.6, 0.2),
 (0.3,   0, 0.7),
  (0.5,   0, 0.5)
  ])

# mostramos el contenido de la matriz A:
print(A)


[[0.2 0.6 0.2]
 [0.3 0.  0.7]
 [0.5 0.  0.5]]


Seguimos calculando con los vectores $\pi_1$ y $\pi_2$ partiendo con $\pi_0$, variables `pi1`, `p2` y `pi0` en el código respectivamente.

Primero $\pi_1$.

In [3]:

# Creamos el vector pi0
pi0 = np.array([0,1,0])

# Calculamos el vector pi1 usando el producto punto con A
pi1 = pi0.dot(A)
# Mostramos el contenido del vector pi1:
print(pi1)

[0.3 0.  0.7]


Ahora $\pi_2$

In [4]:
# pi2 por A
pi2 = pi1.dot(A)
# Mostramos el contenido del vector pi1:
print(pi2)

[0.41 0.18 0.41]


Finalmente $\pi_2 \cdot A$, que sí es un estado estacionario.

In [6]:
resultado = pi2.dot(A)
print(resultado)


[0.341 0.246 0.413]
