# Cadenas de Markov - EN CONSTRUCCIÓN
---
**Competencias de requisito:**
- Probabilidades condicionales.
- Álgebra lineal.
- Python.
- Numpy.
---
**Instrucciones:**

Revise este video (visitado en julio 2023) [Markov Chains Clearly Explained! Part - 1](https://youtu.be/i3AkTO9HLXo) y luego revise el código en Python a continuación.

**Conceptos importantes:**

- Matriz de transición.
- Randomwalk.
- 

(Sólo a modo de referencia sobre **Cadenas de Markov**, puede visitar la lista completa del video anterior en [Markov Chains Clearly Explained!](https://www.youtube.com/playlist?list=PLM8wYQRetTxBkdvBtz-gw8b9lcVkdXQKV))


---
La siguiente es una imagen extraída del video referenciado anteriormente y es un ejemplo de una **Cadena de Markov** 

![Cadena de ejemplo del restaurante](../imagenes/cadena-de-restaurante.png)

**Propiedades de una Cadena de Markov:**

1. _"un estado depende exclusivamente del estado previo y no de la secuencia completa de pasos anteriores"_. Matemáticamente:


$P(X_n=x_n|X_1=x_1,X_2=x_2,...,X_{n-1}=x_{n-1}) = P(X_n=x_n|X_{n-1}=x_{n-1})$


2. _"la suma de los pesos de salida de cada una de las flechas de cualquier estado es igual a 1"_. 


En el video como ejemplo muestra una cadena de platos en tres días consecutivos (tres estados) y se quiere calcular la probabilidad de que al cuarto día se cocine hamburguesas.

![Tres estados](../imagenes/tres-estados.png)


Luego se lleva el problema a un problema de álgebra lineal, donde los pesos de las flechas se especifican en una matriz A, denominada _**matriz de transición**_. La siguiente imagen muestra esta matriz.

![Cadena y matriz](../imagenes/cadena-y-matriz.png)

El **objetivo** planteado en el video es _"encontrar las probabilidades de cada estado"_, para lo que se define un vector $\pi$. Sus elementos corresponden a las probabilidades de los estados.

Suponiendo que el primero es un día de pizza, el primer vector es $\pi_0 = [0,1,0] $.

Llevémoslo a Python...

El siguiente código resuelve el problema planteado en el video. Nuestro objetivo es calcular el vector resultante $\pi_3$, que corresponde al resultado del producto punto $\pi_2 \cdot A$. Para ello se calculan los vectores intermedios $\pi_1$ y $\pi_2$.

In [5]:
import numpy as np

# Creamos la matriz de transición del problema
A = np.array([(0.2, 0.6, 0.2),
 (0.3,   0, 0.7),
  (0.5,   0, 0.5)
  ])

# mostramos el contenido de la matriz A:
print(A)

[[0.2 0.6 0.2]
 [0.3 0.  0.7]
 [0.5 0.  0.5]]


Calculamos los vectores $\pi_1$ y $\pi_2$ partiendo con $\pi_0$. Las variables `pi0`, `pi1` y `pi2` corresponden a los vectores respectivos.

Primero $\pi_1$.

In [6]:

# Creamos el vector pi0
pi0 = np.array([0,1,0])

# Calculamos el vector pi1 usando el producto punto con A
pi1 = pi0.dot(A)
# Mostramos el contenido del vector pi1:
print(pi1)

[0.3 0.  0.7]


Ahora $\pi_2$

In [7]:
# pi2 por A
pi2 = pi1.dot(A)
# Mostramos el contenido del vector pi1:
print(pi2)

[0.41 0.18 0.41]


Finalmente el vector $\pi_3 = \pi_2 \cdot A$, que corresponde a la probabilidad de que en el tercer día haya cualquier de los tres platos.

In [8]:
pi3 = pi2.dot(A)
print(pi3)

[0.341 0.246 0.413]


Ahora el autor del video hace lo mismo pero ya habiendo pasado diez días.

**Random walk**


lo ideal es que se busca calcular un vector de probabilidades $\pi_n$, cuando $n \to \infty$.


muestra que este vector converge a $[0.35191, 0.21245, 0.435164]$.

In [3]:
import numpy as np
import random as rnd

def vector(e0, A, n):
    
    e = e0 # ej: e en {"H", "P", "C"}
            # o sea partimos con hamburgesa
    for i in range(n):
        r = rnd.random()
        e.dot(A)


        pi = pi.dot(A)
    return pi

estados = {"H", "P", "C"}
H={"H":0.2, "P":0.6 , "C":0.2}
P={"H":0.3, "P":0.0 , "C":0.7}
C={"H":0.5, "P":0.0 , "C":0.5}

A = np.array([(0.2, 0.6, 0.2),
 (0.3,   0, 0.7),
  (0.5,   0, 0.5)
  ])
pi0 = np.array([1,0,0])

# [0.35191, 0.21245, 0.435164]  
pi = vector(pi0,A, 100000)
print(pi, " ", sum(pi))


[0.35211268 0.21126761 0.43661972]   0.9999999999999997


En el video

### Estado de equilibrio o distribución estacionaria

Corresponde a la distribución de probabilidades de los estados de una cadena de Markov que deja de cambiar en el tiempo.

En el video, su autor muestra que este vector converge a $[0.35191, 0.21245, 0.435164]$.

In [10]:
pi = np.array([0.35191, 0.21245, 0.43564])

sum(pi)


1.0

## Resolviendo un sistema de ecuaciones lineales

A modo de repaso o recordatorio, se recomienda visitar [esta web](https://www.analyticslane.com/2018/10/29/sistemas-de-ecuaciones-lineales-con-numpy/) donde encontramos información de cómo solucionar un sistema de ecuaciones lineales usando Python.